include("functions/ackley.jl")
include("functions/beale.jl")
include("functions/bohachevsky1.jl")
include("functions/bohachevsky2.jl")
include("functions/bohachevsky3.jl")
include("functions/booth.jl")
include("functions/branin.jl")
include("functions/bukin6.jl")
include("functions/colville.jl")
include("functions/dixonprice.jl")
include("functions/dropwave.jl")

include("functions/sphere.jl")
include("functions/sumsquare.jl")